---

- name: installation of basic packages
  include_tasks: "install_packages.yml"

- name: fix network setup
  include_tasks: "fix_network_setup.yml"

- name: setup locales
  include_tasks: "setup_locales.yml"

- name: setup sshd
  include_tasks: "setup_sshd.yml"

- name: setup timesyncd
  include_tasks: "setup_timesyncd.yml"

- name: setup exim4 local relay
  include_tasks: "setup_exim4.yml"

- name: setup unattended-upgrades
  include_tasks: "setup_unattended_upgrades.yml"

- name: setup node-exporter
  include_tasks: "setup_node_exporter.yml"
