---

- name: install unattended-upgrades
  become: true
  package:
    name:
      - 'unattended-upgrades'
      - 'apt-listchanges'

- name: configure apt-listchanges
  become: true
  template:
    src: listchanges.conf
    dest: '/etc/apt/listchanges.conf'

- name: configure unattended-upgrades
  become: true
  debconf:
    name: unattended-upgrades
    question: 'unattended-upgrades/enable_auto_updates'
    vtype: string
    value: 'true'
  tags:
    - debconf

- name: reconfigure unattended-upgrades
  become: true
  command: dpkg-reconfigure -fnoninteractive unattended-upgrades

- name: set unattended-upgrades notification mail
  become: true
  lineinfile:
    dest: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: '^(//)?Unattended-Upgrade::Mail "'
    line: 'Unattended-Upgrade::Mail "{{ base_unattended_upgrades_notification_mail }}";'