---
pihole_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIGGTCCBAGgAwIBAgIBDTANBgkqhkiG9w0BAQsFADCBkTELMAkGA1UEBhMCREUx
  EDAOBgNVBAgMB0JhdmFyaWExDzANBgNVBAcMBk11bmljaDEZMBcGA1UECgwQSG9t
  ZSBBbmRyZSBLdXBrYTEbMBkGA1UEAwwSaG9tZS5hbmRyZWt1cGthLmRlMScwJQYJ
  KoZIhvcNAQkBFhhtZS1jb250YWN0QGFuZHJla3Vwa2EuZGUwHhcNMjEwMzA2MTE1
  MzQxWhcNMzEwMzA0MTE1MzQxWjByMSUwIwYDVQQDExxwaWhvbGUtbmcuaG9tZS5h
  bmRyZWt1cGthLmRlMQswCQYDVQQGEwJERTEQMA4GA1UECBMHQmF2YXJpYTEPMA0G
  A1UEBxMGTXVuaWNoMRkwFwYDVQQKExBIb21lIEFuZHJlIEt1cGthMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu32f/ggHpzNml70XimmhdccosC3fvN69
  mLSwo7qPm6VQW8wsZ9bKs6y8WyffnrquEbSRFKaGWLk7wXVNGi2yGOBbw2ZwRqC0
  nGIg2Kehh9+szBwciVMuZbO+SxdIcSeUaaKGx7ezkww1bWG/ihTrZJWEKanLHh+a
  lpEQEnNJlHB6G08DnJD03UbfyI25ZLTOaAWcNm/UODuVU70AwVQLDhNmUQmfV65m
  X2W/rPm1uw292p76SBx2o6iWtGlZYSfkP1lpFLZamr7OYn6QOSCcvvgEmiLGMXxq
  Dq2y2joqgm2a4hRIPPr4oEH6bRVvQVcTPhEJ4jdzht3n1diBAIFePQIDAQABo4IB
  mDCCAZQwCQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBkAwCwYDVR0PBAQDAgWg
  MDMGCWCGSAGG+EIBDQQmFiRPcGVuU1NMIEdlbmVyYXRlZCBTZXJ2ZXIgQ2VydGlm
  aWNhdGUwHQYDVR0OBBYEFK8h/KBqEMBiwQQXEWHptnqYF3/yMIHABgNVHSMEgbgw
  gbWAFE9sgsPsgK+g/5UPDq4NSRSFTw/YoYGXpIGUMIGRMQswCQYDVQQGEwJERTEQ
  MA4GA1UECAwHQmF2YXJpYTEPMA0GA1UEBwwGTXVuaWNoMRkwFwYDVQQKDBBIb21l
  IEFuZHJlIEt1cGthMRswGQYDVQQDDBJob21lLmFuZHJla3Vwa2EuZGUxJzAlBgkq
  hkiG9w0BCQEWGG1lLWNvbnRhY3RAYW5kcmVrdXBrYS5kZYIDftcJMCcGA1UdJQQg
  MB4GCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUIAgIwJwYDVR0RBCAwHoIccGlo
  b2xlLW5nLmhvbWUuYW5kcmVrdXBrYS5kZTANBgkqhkiG9w0BAQsFAAOCAgEABZPj
  HarcR5MQ8gKYD8+raOTaIiMgyCi3vOoHsR1kkQrdQmHn7hoZeyOO9dUP9Ooqz4CL
  NBq8YxgksOHZmhLxwkewAS2UYnH37rsI43v2tFXY7XEDgrxwoqD1h+eOw2d6S2nO
  LcB+AJU3rFPToAY9t62i6p7SwYGvhYC6/Xmc+wCNSOwiTHZ9mw7UCywKQ+3HbiLP
  k3W5IShkQa4kfFBIi9qr+mwhjboQpj9Ayu04e++E/J+TfS/GsGLrvlefN3xHDdeu
  p+35SuWTR/C0Q2VI0xSPJliC/2js3pCtBV5UosjUcXfq2E0x0W6XFqGVD8y1O7KK
  cxX1ti2+qhzIeQbS9KNDFY1z5fBJvlIVO33We5+/cQewpr+Q24mzZ1u9I4VlfYnM
  hEGwkIuGcGHcs+qziAV5UTMpytIu5/p5ic5GKR8lAQ2V19i0d47QHXVxz+RHJytb
  1AAqtf4XjnK9bn1VNod6QbOaJ2ODiwZ2ejYeb/CguawlLHWtd/bmhgiK1jjVjfIT
  b++6ZW7JvE/mWbRWsfjP4qF77bK6kxWy+7LvLqn7vYs3qkFwkqV/CCmXW+ou48YZ
  dIl8GnXsa5zfnG03XKocLGdJAn8RFVnE/MXo07ZfVtFAcZros85U4Hr9MUUBt1//
  aBR3lPOm7xCdg/TuJDi5XUpBmJWXqtsY2ewVPXU=
  -----END CERTIFICATE-----
